import React from 'react';
import { Github, Globe } from 'lucide-react';

interface FooterProps {
  onOpenModal: (type: string) => void;
}

export const Footer: React.FC<FooterProps> = ({ onOpenModal }) => {
  const links = [
    { label: 'About', key: 'about' },
    { label: 'Contact', key: 'contact' },
    { label: 'Guide', key: 'guide' },
    { label: 'Privacy Policy', key: 'privacy' },
    { label: 'Terms of Service', key: 'terms' },
    { label: 'DMCA', key: 'dmca' },
  ];

  return (
    <footer className="w-full border-t border-white/5 bg-[#030407]/90 backdrop-blur-2xl relative z-20 mt-auto">
      <div className="container mx-auto px-6 py-12">
        <div className="flex flex-col md:flex-row justify-between items-center gap-8">
          
          {/* Brand Identity */}
          <div className="text-center md:text-left space-y-2">
            <h3 className="text-2xl font-bold text-white tracking-tight flex items-center gap-2 justify-center md:justify-start">
              Doodax<span className="text-indigo-500">.com</span>
            </h3>
            <p className="text-sm text-gray-500">Professional Legal Automation Tools</p>
          </div>

          {/* Legal Navigation */}
          <div className="flex flex-wrap justify-center gap-x-8 gap-y-3 text-sm font-medium text-gray-400">
            {links.map((link) => (
              <button
                key={link.key}
                onClick={() => onOpenModal(link.key)}
                className="hover:text-indigo-400 transition-colors relative group"
              >
                {link.label}
                <span className="absolute -bottom-1 left-0 w-0 h-px bg-indigo-500 transition-all group-hover:w-full"></span>
              </button>
            ))}
          </div>

          {/* Developer Credit */}
          <div className="flex flex-col items-center md:items-end gap-3">
             <div className="flex items-center gap-4">
                <a 
                  href="https://github.com/hsinidev" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="group flex items-center gap-2 text-sm text-gray-400 hover:text-white transition-all bg-white/5 px-4 py-2 rounded-full border border-white/5 hover:border-indigo-500/30 hover:bg-indigo-500/10 hover:shadow-lg hover:shadow-indigo-500/10"
                >
                  <span className="text-xs uppercase tracking-wider text-gray-500 group-hover:text-indigo-300">Powered by</span>
                  <span className="font-bold text-white">HSINI MOHAMED</span>
                  <Github className="w-4 h-4 ml-1 text-gray-400 group-hover:text-white" />
                </a>
             </div>
             <p className="text-xs text-gray-600">© {new Date().getFullYear()} Doodax. All rights reserved.</p>
          </div>
        </div>
        
        <div className="mt-10 pt-6 border-t border-white/5 text-center">
            <p className="text-[10px] text-gray-600 max-w-2xl mx-auto leading-relaxed">
                Disclaimer: The documents generated by this tool are for informational purposes only and do not constitute legal advice. Doodax is not a law firm. Please consult with a qualified attorney for all legal matters.
            </p>
        </div>
      </div>
    </footer>
  );
};